on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  setup:
    name: Create matrix
    runs-on: ubuntu-latest
    steps:
      - id: matrix
        run: |
          gcs_domains="${{ env.GCS_PUBLIC_DOMAINS }}"
          echo "::set-output name=matrix-gcs-domains::[\"${gcs_domains//', '/\",\"}\"]"
    outputs:
      matrix-gcs-domains: ${{ steps.matrix.outputs.matrix-gcs-domains }}

  set-gcs-cache-control:
    needs: [setup]
    name: Set GCS Cache-Control
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix-gcs-domains)}}
    steps:
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Echo values from ENV
        run: |
          gsutil -m setmeta -r -h "Cache-control:public, max-age=15778463" gs://${{ matrix.value }}
